### Test Get
GET https://localhost:7192/api/ScriptGeneratorApi/test/ HTTP/1.1 


### Test with Default Data
POST https://localhost:7192/api/ScriptGeneratorApi/generatescript/ HTTP/1.1
content-type: application/json

{
	"TemplateName": "Umbraco.Templates",
	"TemplateVersion": "",
	"Packages": "",
	"CreateSolutionFile": false,
	"SolutionName": "MySolution",
	"ProjectName": "MyProject",
	"ConnectionString": "",
	"UserFriendlyName": "Administrator",
	"UserEmail": "admin@example.com",
	"UserPassword": "1234567890",
	"IncludeStarterKit": true,
	"StarterKitPackage": "clean",
	"UseUnattendedInstall": true,
	"DatabaseType": "SQLite",
	"OnelinerOutput": false,
	"RemoveComments": false
}


### Test with Empty Data
POST https://localhost:7192/api/ScriptGeneratorApi/generatescript/ HTTP/1.1
content-type: application/json

{
	"TemplateName": "",
	"TemplateVersion": "",
	"Packages": "",
	"CreateSolutionFile": false,
	"SolutionName": "",
	"ProjectName": "",
	"ConnectionString": "",
	"UserFriendlyName": "",
	"UserEmail": "",
	"UserPassword": "",
	"IncludeStarterKit": false,
	"StarterKitPackage": "",
	"UseUnattendedInstall": false,
	"DatabaseType": "",
	"OnelinerOutput": false
}


### Test with Partially Set Data
POST https://localhost:7192/api/ScriptGeneratorApi/generatescript/ HTTP/1.1
content-type: application/json

{
	"TemplateName": "Umbraco.Templates",
	"TemplateVersion": "",
	"Packages": "uSync,uSync.Complete",
	"CreateSolutionFile": true,
	"SolutionName": "MySolution",
	"ProjectName": "MyProject",
	"ConnectionString": "",
	"UserFriendlyName": "",
	"UserEmail": "admin@example.com",
	"UserPassword": "1234567890",
	"IncludeStarterKit": true,
	"StarterKitPackage": null,
	"UseUnattendedInstall": true,
	"DatabaseType": "SQLite",
	"OnelinerOutput": false
}
